feat:Import statement
arxlang/astx pull request #118
Opened 2024-10-04 13:20 UTC by apkrelling

## Pull Request description

This PR adds AliasExpr, ImportStmt and ImportFromStmt. 
This PR is an attempt to solve #87 .

- [X] added new ASTKind's
- [X] created AliasExpr, ImportStmt and ImportFromStmt classes
- [X] updated `__init__.py` to include the new imports and classes in the `__all__` list
- [X] added the new classes ad visit methods in `transpilers/python.py`
- [X] added tests in `tests/transpilers/test_python.py`
- [X] added tests in `tests/test_packages.py`

## How to test these changes

```python
from astx.transpilers import python as astx2py

from astx.packages import (
    AliasExpr,
    ImportFromStmt,
)

# Create an import-from statement
alias3 = AliasExpr(name="path", asname="p")
import_from_stmt = ImportFromStmt(module="os", names=[alias3], level=0)

# Initialize the generator
generator = astx2py.ASTxPythonTranspiler()

# Generate Python code
generated_code = generator.visit(import_from_stmt)

# print generated code
generated_code
``` 
```python
from astx.packages import (
    AliasExpr,
    ImportFromStmt,
)

alias3 = AliasExpr(name="path", asname="p")

import_from_stmt = ImportFromStmt(
    module="os", names=[alias3], level=0
)

import_from_stmt.get_struct()
import_from_stmt.get_struct(simplified=True)

```

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [X] new feature
- [ ] maintenance

About this PR:

- [X] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [X] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more
      complexity.
- [X] New and old tests passed locally.

## Additional information

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

2024-10-04 13:32 UTC, apkrelling commented
Things to discuss about this PR:
- multiple imports
- should we make changes to handle wildcard imports?
- should we do something to add support for `from __future__ import`s ?
- should we extend `AliasExpr` (Additional considerations, number 3 [in the issue](https://github.com/arxlang/astx/issues/87))
- should we modify the code to represent `import *` in `ImportStmt`?
 

TO-DO:
- add more tests for edge cases and error handling
- check if there's any documentation that should be updated

2024-10-05 19:12 UTC, apkrelling commented
Updates to this PR:
- added tests
- added support for multiple imports (in the transpiler visit method for `ImportStmt`)
- added support for wildcard, relative, and `from __future__` imports

TO-DO:
- integration with `ASTNodes` is not working yet

2024-10-05 19:24 UTC, apkrelling commented
There are some inconsistencies when it comes to testing the implementation.

In the issue, it stated that the code below
```python

# Create aliases
alias1 = AliasExpr(name="math")
alias2 = AliasExpr(name="os", asname="operating_system")

# Create an import statement
import_stmt = ImportStmt(names=[alias1, alias2])

# Print the string representation
print(import_stmt)

# Print the AST structure
print(import_stmt.to_yaml())
```
should have the expected output:
![expected_output](https://github.com/user-attachments/assets/9fd357d7-9b62-4e5d-be2c-6e9ab84ce4c2)

but instead, it has this output:
![generated_output](https://github.com/user-attachments/assets/b44c1409-b891-4f85-b67f-2d5a82054b0f)

but the generated output for 
```python
# Print the string representation
print(import_stmt)

# Print the AST structure
print(import_stmt.to_yaml(simplified=True))
```
is the one below. So it's (mainly) an issue of the `simplified=True` argument.
![simplified_output](https://github.com/user-attachments/assets/91e57bc5-318e-4296-a2b5-c86112e8d954)

2024-10-05 20:30 UTC, apkrelling commented
When it comes to the integration with ASTNodes, in the issue it was suggested this
```python
module_ast = ASTNodes(name="module")
module_ast.append(import_stmt)
module_ast.append(import_from_stmt)

# Print the module's AST structure
print(module_ast.to_yaml())
```
and this did not work with the code as it it. However, the code below
```python
from astx.packages import (
    AliasExpr,
    ImportFromStmt,
    ImportStmt,
)
from astx.packages import Module

alias1 = AliasExpr(name="math")
alias2 = AliasExpr(name="os", asname="operating_system")
import_stmt = ImportStmt(names=[alias1, alias2])

alias3 = AliasExpr(name="path", asname="p")
import_from_stmt = ImportFromStmt(module="os", names=[alias3], level=0)

import_module = Module()
import_module.append(import_stmt)
import_module.append(import_from_stmt)
print(import_module.to_yaml(simplified=True))
```
generates the following output:

> MODULE[main]:
> - Import:
>   \- Alias:
>       name: math
>   \- Alias:
>       name: os
>       asname: operating_system
> \- ImportFrom:
>     module: os
>     level: 0
>     names:
>     \- Alias:
>         name: path
>         asname: p

We can discuss this during our next meeting, if you'd like.

2024-10-07 17:26 UTC, xmnlab requested changes

2024-10-07 17:26 UTC, xmnlab commented on src/astx/packages.py
> +        asname: Optional[str] = None,
```suggestion
        asname: str = "",
```

2024-10-07 17:26 UTC, xmnlab commented on src/astx/packages.py
> +        module: Optional[str] = "",
```suggestion
        module: str = "",
```

2024-10-07 17:26 UTC, xmnlab commented on src/astx/packages.py
> +        if isinstance(names, list):
please remove this `isinstance` validation, because it will be done via typeguard

2024-10-07 17:26 UTC, xmnlab commented on src/astx/transpilers/python.py
> +        if not isinstance(node.names, list):
please remove this `isinstance` validation, because it will be done via typeguard

2024-10-07 21:13 UTC, apkrelling commented
@xmnlab , I've made all the changes you requested in this PR. I believe it is good to go.

2024-10-07 21:37 UTC, xmnlab approved these changes
LGTM! thanks for working on that @apkrelling 
great job here :)

2024-10-07 21:39 UTC, merged